import { createServer } from 'http';
import fs from 'fs'; import path from 'path';
import { createRequire } from 'module';
const puppeteer = createRequire('/Users/atlas/drive/recipe/node_modules/x.js')('puppeteer');
const ROOT = '/Users/atlas/404_jam_site';
const MIME = { '.html':'text/html','.mp4':'video/mp4','.jpg':'image/jpeg','.png':'image/png','.css':'text/css','.js':'text/javascript','.woff2':'font/woff2' };
const server = createServer((req,res)=>{ let rel=decodeURIComponent(req.url.split('?')[0]); if(rel==='/')rel='/index.html';
  const f=path.join(ROOT,rel); if(!f.startsWith(ROOT)||!fs.existsSync(f)||fs.statSync(f).isDirectory()){res.writeHead(404);return res.end();}
  res.writeHead(200,{'Content-Type':MIME[path.extname(f)]||'application/octet-stream','Cache-Control':'no-store'}); fs.createReadStream(f).pipe(res); });
await new Promise(r=>server.listen(0,'127.0.0.1',r));
const BASE=`http://127.0.0.1:${server.address().port}/`;
const browser = await puppeteer.launch({headless:true,args:['--no-sandbox','--enable-unsafe-swiftshader','--autoplay-policy=no-user-gesture-required']});
const W = +(process.argv[2]||1440);
const HASH = process.argv[3]||'';
const page = await browser.newPage();
await page.setViewport({width:W,height:900,deviceScaleFactor:1});
await page.goto(BASE+HASH,{waitUntil:'networkidle2'});
await new Promise(r=>setTimeout(r,1200));
const out = await page.evaluate(()=>{
  const R=[];
  const push=(label,el)=>{ if(!el) return; const r=el.getBoundingClientRect(); const cs=getComputedStyle(el);
    R.push({label, x:+r.left.toFixed(1), r:+r.right.toFixed(1), y:+r.top.toFixed(1), b:+r.bottom.toFixed(1), w:+r.width.toFixed(1), h:+r.height.toFixed(1),
      pad:cs.padding, mt:cs.marginTop, mb:cs.marginBottom, fs:cs.fontSize, lh:cs.lineHeight,
      bl:cs.borderLeftWidth+' '+cs.borderLeftColor, br:cs.borderRightWidth, bt:cs.borderTopWidth, bb:cs.borderBottomWidth}); };
  const q=(s)=>document.querySelector(s);
  const qa=(s)=>[].slice.call(document.querySelectorAll(s));
  push('wrap#what', q('#what .wrap'));
  push('lab#what', q('#what .lab'));
  push('h2#what', q('#what h2'));
  push('lead#what', q('#what .lead'));
  push('gal', q('.gal'));
  qa('.gal .shotcell').slice(0,3).forEach((e,i)=>push('shotcell'+i,e));
  qa('.gal .cap').slice(0,3).forEach((e,i)=>push('cap'+i,e));
  push('stats', q('.stats'));
  qa('.stat').forEach((e,i)=>push('stat'+i,e));
  push('stat0 b', q('.stat b')); push('stat0 span', q('.stat span'));
  push('steps', q('.steps'));
  qa('.step').forEach((e,i)=>push('step'+i,e));
  push('step0 n', q('.step .n')); push('step0 h3', q('.step h3')); push('step0 p', q('.step p'));
  push('prizes', q('.prizes'));
  qa('.prize').forEach((e,i)=>push('prize'+i,e));
  push('prize0 pix', q('.prize .pix')); push('prize0 amt', q('.prize .amt')); push('prize0 p', q('.prize p'));
  push('time', q('.time'));
  qa('.tcell').forEach((e,i)=>push('tcell'+i,e));
  push('tcell0 pix', q('.tcell .pix')); push('tcell0 d', q('.tcell .d')); push('tcell0 p', q('.tcell p'));
  push('prizes-spec-wrap', qa('#prizes .wrap')[1]);
  push('prizes-spec', q('#prizes .spec'));
  push('gate cols', q('#gate .cols'));
  push('gate col1', q('#gate .cols > div'));
  push('gate col2', qa('#gate .cols > div')[1]);
  push('gate lab', q('#gate .lab')); push('gate h2', q('#gate h2')); push('gate spec', q('#gate .spec'));
  push('gate spec row0', q('#gate .spec > div')); push('gate k0', q('#gate .spec .k')); push('gate v0', q('#gate .spec .v'));
  push('faq', q('.faq')); push('faq sum0', q('.faq summary'));
  push('footer wrap', q('footer .wrap'));
  push('promptwrap', q('.promptwrap')); push('prompt wrap', q('.promptwrap .wrap')); push('lbl', q('.promptwrap .lbl'));
  push('beamwrap', q('.beamwrap')); push('panel', q('.panel')); push('panel inner', q('.panel .inner')); push('panel code', q('.panel code'));
  push('stage in wrap', q('.stage .in .wrap')); push('h1', q('h1')); push('tagline', q('.stage .tagline')); push('stage row', q('.stage .row'));
  push('bar wrap', q('.bar .wrap'));
  push('sec what', q('#what')); push('sec how', q('#how')); push('sec gate', q('#gate')); push('sec prizes', q('#prizes')); push('sec dates', q('#dates'));
  push('how wrap', q('#how .wrap')); push('how lab', q('#how .lab')); push('how h2', q('#how h2'));
  push('prizes wrap', q('#prizes .wrap')); push('prizes lab', q('#prizes .lab')); push('prizes h2', q('#prizes h2'));
  push('dates wrap', q('#dates .wrap'));
  return R;
});
console.log(out.map(o=>`${o.label.padEnd(18)} x=${String(o.x).padStart(7)} r=${String(o.r).padStart(7)} y=${String(o.y).padStart(8)} b=${String(o.b).padStart(8)} w=${String(o.w).padStart(7)} h=${String(o.h).padStart(6)} pad=${o.pad} mt=${o.mt} mb=${o.mb} fs=${o.fs} lh=${o.lh} bL=${o.bl} bR=${o.br} bT=${o.bt} bB=${o.bb}`).join('\n'));
await browser.close(); server.close();
